### ISSUE TITLE
Entering any value as access token makes mCaptcha pass the connection.

### ISSUE THREAD

**Issue by GamePlayer-8** [mCaptcha/mCaptcha#155]
Good morning yet again,

I've noticed that regardless of what I type as access token on the client side, mCaptcha will authorize me to use SiteKey (shows `Verified!` in the embed and returns the positive statement).

It should refuse my request when I provide the wrong access token and show the error in the embed.

**Comment by realaravinth** [comment]
The authorization token is autogenerated by mCaptcha. It should be presented by the client to the protected service with the request that's trying to access the protected resource.

Whether the client is presenting the right access token or not is irrelevant to the widget, if it is presenting a wrong access token, then it's probably an error on the client.

**Comment by realaravinth** [comment]
I'm sorry, but I don't understand what you are trying to do. Authorization token (used to be access token), is automatically set by the widget upon successful challenge solve. Outside of that, authorization token doesn't mean anything to the widget.

Can you please share source code for the client? At least just the part where you are integrating the widget?

**Comment by realaravinth** [comment]
That's so cool! The Misskey part, not the stuff you are experiencing. :p

The secret key doesn't affect the captcha. If the secret key's wrong, then the backend (miskey in this case), won't be able to validate the authorization token (used to be access token) submitted by the client.

Since this is a FOSS effort, I'd love to help if you'd prefer a more real-time communications channel.

**Comment by realaravinth** [comment]
[We have a Matrix room](https://matrix.to/#/%23mCaptcha%3Amatrix.batsense.net?via=matrix.batsense.net&via=matrix.org&via=obermui.de&via=grin.hu)
