### ISSUE TITLE
Can't login using docker compose installation

### ISSUE THREAD

**Issue by CartierPierre** [mCaptcha/mCaptcha#32]
Hi, it's me again,
I'm using docker-compose installation.
I tried to login use default credentials or create new one but it's not working.
It redirects me to login page.
I see the INSERT in the log when creating an account, and the SELECT, but it says `from conversin: Account not found`

**Comment by realaravinth** [comment]
Hello again!

I will require more information such as server logs(`docker-compose logs -f`) and the login request and response logs from the browser development tools to figure out what is really going on as there are multiple tests to ensure that authentication routes are working as expected.

But, I think this issue arises from the web framework that mCaptcha uses: mCaptcha is, by default, configured to serve localhost:7000. So accessing the app at http://localhost:7000 should work but http:/127.0.0.1:7000 or with any other hostname won't because of how the web framework's session middleware works.

So I recommend accessing the app at http://localhost:7000 to see if it resolves the issue.

**Comment by CartierPierre** [comment]
Oh, I'm running it on a server, so I call it http://myserve:7000. I can't use localhost for the server

**Comment by CartierPierre** [comment]
Perfect ! Thanks again
