### ISSUE TITLE
docker/podman build error

### ISSUE THREAD

**Issue by megheaiulian** [mCaptcha/mCaptcha#59]
Trying to build this project: 

I am getting a 
>error: couldn't read src/../docs/openapi/dist/openapi.yaml: No such file or directory (os error 2)

when I run  `podman build -t mcaptcha/mcaptcha:latest .`

![image](https://user-images.githubusercontent.com/1788114/211803376-220136bd-af75-4034-89a1-bf338d99a074.png)

**Comment by realaravinth** [comment]
I tried setting up podman, I've never worked with it before. I was facing issues, so I was going to get to it in the morning, but I'm glad it works?  :sweat_smile: 

The Dockerfile contains a step to build the frontend, I'm not sure why it didn't work in podman though.

**Comment by megheaiulian** [comment]
I don't think this is `podman` specific. It should work almost the same way as docker.  
I think that because I cloned the folder in a new folder I didn't had the `docs/openapi/dist` folder built when i run the build.

**Comment by megheaiulian** [comment]
@serviliosouza to fix that you need to install node and yarn. Run 'yarn install' in the docs  folder and then 'yarn build'.

**Comment by realaravinth** [comment]
Apologies for the delay, offline commitments kept me busy :sweat_smile: 

Build assets weren't being copied over to the final stage container from the build container. The container was building successfully on my dev machine and on the CI because `node_modules` and the build assets were present in host environments and was copied into the final stage container.

I've manually verified that the container is building on a fresh clone of this repository. If the problem still exists, please feel free to reopen the issue.
