### ISSUE TITLE
mcaptcha.org down

### ISSUE THREAD

**Issue by simplePCBuilding** [mCaptcha/mCaptcha#61]
I have noticed that mcaptcha.org is not online anymore. Do you know what happened or is it intentional?

**Comment by realaravinth** [comment]
Thanks for reporting! The server hosting mCaptcha infrastructure suffered a hardware failure and is down for almost 36h now. I am unable to get spare parts due to a lengthy local festival. I've been trying for almost two days now, but with no luck.

It will be online tomorrow if I can get the spares, otherwise it will take me a week to migrate to a different machine.

If you'd like to browse the contents of mcapthca.org, it is available at https://mcaptcha.github.io/website/. Styling is broken because the site designed to be published at root, but the content should be readable.

**Comment by simplePCBuilding** [comment]
Yeah I have seen that. That explains a lot. I noticed that mcaptcha was slower over the last few days before it stopped working. What died exactly? A drive?

**Comment by realaravinth** [comment]
The server was running hot for the last few days, but I put it down to increased load. I still had some legroom, and I was going to add a new machine, so I wasn't worried about it. But the extra load wasn't the only reason it was hot, the fans were failing, so the CPU was probably being throttled.

As for disk, I think it is good for now. I have backups, so I'm not worried about it for the moment :sweat_smile:

**Comment by realaravinth** [comment]
Hello,

mcaptcha.org was restored back online on 7th February, I'm sorry I didn't report earlier.

I'm closing this ticket, feel free to reopen if you find the issue to be unresolved. 

Thanks o/
